### ISSUE TITLE
missing include sqlpp11/chrono

### ISSUE THREAD

**Issue by MichaelMiller-** [rbock/sqlpp11-connector-sqlite3#13]
I'm trying to use the sqlite3 connector but the compiler is missing some file. 
```
/include/sqlpp11/sqlite3/prepared_statement.h:32:28: fatal error: sqlpp11/chrono.h:
No such file or directory

```

**Comment by rbock** [comment]
Hi Michael,

As far as I can tell, it works fine with the current release of sqlpp11.

If you still have an issue here, please let me know which versions you are using.

Thanks,

Roland

**Comment by MichaelMiller-** [comment]
Hi Roland

It seems to be my fault :-) I remove the current repository and clone it again, now everything works fine. Sorry for bother you.

Best Regards
Michael
