### ISSUE TITLE
suggestion: add "date" dependency to README

### ISSUE THREAD

**Issue by MichaelMiller-** [rbock/sqlpp11-connector-sqlite3#14]
hi
it would be nice if somewhere (e.g. README.md) is mentioned that this project depends on this repository [https://github.com/HowardHinnant/date](https://github.com/HowardHinnant/date).

best regards
michael

**Comment by rbock** [comment]
Hi Michael,

Thanks for the hint! I thought it was implicitly clear because sqlpp11 depends on Howard's date library. I made it explicit now.

Best,

Roland
