### ISSUE TITLE
prepare_statement returns a deallocated statement handle

### ISSUE THREAD

**Issue by isliser** [rbock/sqlpp11-connector-sqlite3#15]
The problem is in `prepared_statement_handle_t(prepared_statement_handle_t&&)` that does not set sqlite_statement to null.

Tested in msvs 2015

**Comment by rbock** [comment]
Ooops, that sounds scary. Thanks!

**Comment by rbock** [comment]
Should be fixed on master now. Please check.

**Comment by isliser** [comment]
It works now

**Comment by rbock** [comment]
Thanks for testing!
