### ISSUE TITLE
Unable to use prepared insert with sqlite3 backend

### ISSUE THREAD

**Issue by isliser** [rbock/sqlpp11-connector-sqlite3#16]
```
using namespace sqlpp::sqlite3;

connection_config config{"D:/temp/local.sqlite", SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE};
connection db{config};

const auto p = test::TabPerson{};
        const auto f = test::TabFeature{};
        auto pi = db.prepare(insert_into(p).set(p.name = parameter(f.name), p.feature = parameter(p.feature)));
        pi.params.name = "likes java";
        pi.params.feature = true;
        db(pi);
```

Gives compile error:

> error C2440: 'static_cast': cannot convert from 'const sqlpp::parameter_list_tsqlpp::detail::type_vector<sqlpp::parameter_t<sqlpp::text,T,sqlpp::parameter_tsqlpp::integral,sqlpp::column_t<Table,test::TabPerson_::Feature>>>' to 'test::TabFeature_::Name::_alias_t::_member_tsqlpp::parameter_value_t<sqlpp::text> &'

Meanwhile same insert compiles fine with MockDb
Tested with msvs 2015

**Comment by rbock** [comment]
Do the tests in the sqlite3 connector still compile?

**Comment by isliser** [comment]
No, they don't 
It appears the issue due to ms bugs

**Comment by rbock** [comment]
OK, I will need to set up the connectors with travid and appveyor, but that will take some time (too much to do this week).

Any additional input would be great.

**Comment by rbock** [comment]
Time flies... I got the code to compile on appveyor with the latest release now. As of now the tests seem to run forever. I am not sure how to debug that yet.

**Comment by rbock** [comment]
The sqlite3 connector got merged into sqlpp11.

Closing all issues here, before archiving. If this issue is still relevant, please re-file for sqlpp11.
