### ISSUE TITLE
insert into with truncates floating value

### ISSUE THREAD

**Issue by isliser** [rbock/sqlpp11-connector-sqlite3#17]
```
using namespace sqlpp::sqlite3;

connection_config config{"D:/temp/local.sqlite", SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE};

connection db{config};
connection::_serializer_context_t printer{db};

const auto Test = Test::Test{};

auto query = insert_into(Test).set(Test.Value = 5.54658465132);
auto raw = serialize(query, printer).str();
```

This snippet gives such sql clause:

> INSERT  INTO Test (Value) VALUES(5.54658)

So the value was truncated to 6 digit after point

**Comment by rbock** [comment]
Hmm. Admittedly, I use floats almost never...

I could add a something like http://en.cppreference.com/w/cpp/io/manip/setprecision

What do you think?

**Comment by isliser** [comment]
This will work if use max precision & scientific format
`std::setprecision(std::numeric_limits<long double>::digits10 + 1) << std::scientific << value`

Have you ever thought about using boost::spirit instead of stringstream?

**Comment by rbock** [comment]
OK, I'll add something like that.

Using boost::spirit crossed my mind some years ago. I did not want to add such dependency (and compile time overhead).

It would be rather simple to replace the current string stream with boost::spirit. I would welcome the alternative, if you could offer such a connector. You should be able to reuse almost everything of the existing code and just replace the serializer.

**Comment by dheide** [comment]
First, I really enjoy using sqlpp11. 
I also ran into the problem that my double precision values are truncated. Is there any workaround to ensure that the correct data is written into the db.

**Comment by rbock** [comment]
Thanks for the flowers and the reminder. I lost track of this one.

In sqlpp11, look into `include/sqlpp11/data_types/floating_point/operand.h`. In the specialization of the `serializer_t`, you will see `context << t._t;`, where `t._t`  is your double value and `context` is a wrapped `std::ostream`.

Also in the sqlite3 connector, look into `include/sqlpp11/sqlite3/connection.h`. The `serializer_t` there is the context used in the sqlpp11 library (not exactly perfect naming, I just realized).

It would be great if you could adjust either place to avoid truncation and send in a pull request.

Cheers,

Roland

**Comment by matpen** [comment]
I am affected by this issue, too, which seem to have been set on hold. However, I can confirm that using [prepared statements](https://github.com/rbock/sqlpp11/wiki/Prepared-Statements) correctly avoids the problem, sending the the values with full precision to the database.

As for the fix, I would suggest something like explained [here](https://stackoverflow.com/questions/554063/how-do-i-print-a-double-value-with-full-precision-using-cout), i.e. changing [this line](https://github.com/rbock/sqlpp11/blob/8113a5f1fcb788f7f415e9c3c1771859fe381eb9/include/sqlpp11/data_types/floating_point/operand.h#L74) to:

    context << std::defaultfloat << std::setprecision(std::numeric_limits<Operand::_value_t>::max_digits10) << t._t;

I can provide a pull request. However, being new to the library, I have the following questions:
- is `operand.h` the right spot to do this, or is it better to do it in the connectors (i.e. `include/sqlpp11/sqlite3/connection.h`)? The mysql connector is affected, as well, and I guess all other connectors, too.
- I see that `Operand::_value_t`is hard-coded in `operand.h` to type `double`: can there be cases where a custom type is used, and therefore `std::numeric_limits<T>` will not work?

**Comment by rbock** [comment]
I'll start with the second question:
If somebody uses a custom type, they might have to adjust the serializer, too.

I think it makes sense to adjust `floating_point/operand.h`. However, at least in tests, people could use things like `std::cout` as a stream for serialization. Serializing a floating point number should not have a side effect on that stream (changing the precision). Thus, we need to set the desired precision and then return to the old setting afterwards.

**Comment by matpen** [comment]
That makes sense. For this, we can [interrogate the stream](http://en.cppreference.com/w/cpp/io/ios_base/flags) for its settings, change them, and re-set the original settings:

    const auto old_flags = context.flags();
    const auto old_precision = context.precision();
    context << std::defaultfloat << std::setprecision(std::numeric_limits<Operand::_value_t>::max_digits10) << t._t;
    context.setf(old_flags);
    context.precision(old_precision);

Is this suitable?

**Comment by rbock** [comment]
That's the right direction.

Please also take a look at the save_stream class in Howard Hinnant's date library. It does something very similar in RAII style (we should do that as well).

It also sets and restores the locale. That might be interesting for us, too. But then again, what if the database itself is operating in some strange locale?

**Comment by snikulov** [comment]
@rbock is any progress on this issue? Did anybody use SQLite for scientific data?

**Comment by snikulov** [comment]
The workaround is a prepared statement, where sqlite3_bind_double used.
Sorry for the noise.

**Comment by rbock** [comment]
@snikulov I am glad that is an option for you :-)

**Comment by snikulov** [comment]
@rbock BTW, perhaps for serializer it is good to provide formatter as a parameter for serialized statements.
As another option. Just my thoughts...

**Comment by rbock** [comment]
The sqlite3 connector got merged into sqlpp11.

Closing all issues here, before archiving. If this issue is still relevant, please re-file for sqlpp11.
