### ISSUE TITLE
Is it possible that the whole project can compile and work under android?

### ISSUE THREAD

**Issue by xeoshow** [rbock/sqlpp11-connector-sqlite3#20]
Hi,

Since it is C++ based, I just would like to know Is it possible that the whole project can compile and work under android?

Thanks!

Best regards, Jason

**Comment by rbock** [comment]
Hi Jason,

If you have a compliant C++11 compiler, I see no reason why not.

Let me know if it actually works (or if you run into problems).

Best,

Roland

**Comment by xeoshow** [comment]
Thanks for kind reply. I will feedback when I got the android env. 

Best regards, Jason

**Comment by xeoshow** [comment]
Seems could work and close now. thanks!
