### ISSUE TITLE
Hardcoded paths for the date and sqlpp11 libraries

### ISSUE THREAD

**Issue by przemkovv** [rbock/sqlpp11-connector-sqlite3#24]
The CmakeLists.txt contains two lines that set variables DATE_INCLUDE_DIR and SQLPP11_INCLUDE_DIR with hardcoded paths. I think it would be preferred to leave them, like in the sqlpp11 project, unset and make it possible to user to pass values through  cmake command line.

There are at least two solutions: 
-  just completely remove 'set' commands,
- set them if and only if they weren'y set earlier by user.

**Comment by rbock** [comment]
Sounds good to me. Could you create a pull request?

**Comment by snikulov** [comment]
@rbock can be closed per #39 changes.

**Comment by rbock** [comment]
Right, thanks!
