### ISSUE TITLE
How could I add password for sqlite database when using sqlpp11-connector-sqlite3?

### ISSUE THREAD

**Issue by xeoshow** [rbock/sqlpp11-connector-sqlite3#26]
Hi, 

This project is great, and now I need add password to my sqlite database, How could I add password for sqlite database when using sqlpp11-connector-sqlite3?

Thanks!

**Comment by rbock** [comment]
`connection_config(std::string path, int fl = 0, std::string vf = "", bool dbg = false,std::string password="")`

**Comment by xeoshow** [comment]
Thanks for reply, does this mean I could use this api to create sqlite database with password? And also use this api to connect and use the created database?
Thanks again!

**Comment by rbock** [comment]
Hi,

I guess I misread your question. The library uses `sqlite3_key` (if available) to connect with a password. I don't think you can create a database this way, but I admit I am not an expert for sqlite3 with encryption.

Best,

Roland

**Comment by xeoshow** [comment]
Hi Roland,

Thanks for help!

Does this mean if I create the sqlite database with password, then sqlpp11-connector-sqlite3 can support connecting to it?

**Comment by rbock** [comment]
Assuming that you are using SQLCipher, see also CMakeLists.txt

**Comment by rbock** [comment]
I assume you solved this by now, since I did not hear back from you
