### ISSUE TITLE
ambiguous call to overloaded function	Sqlpp11Sqlite3AttachTest when building on VS2015

### ISSUE THREAD

**Issue by sinall** [rbock/sqlpp11-connector-sqlite3#27]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2668	'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::assign': ambiguous call to overloaded function	Sqlpp11Sqlite3AttachTest	C:\Users\xxx\Documents\Visual_Studio_2015\Projects\sqlpp11-0.46\include\sqlpp11\data_types\text\result_field.h	53	
> 

Environment:
VS2015 Update 1
sqlpp11-connector-sqlite3: 0.23
sqlpp11: 0.46
SQLCipher: 3.4.1 (SQLite: 3.15.2)

**Comment by rbock** [comment]
Thanks, fixed that in sqlpp11.

As mentioned in your sqlpp11 issue, I guess you need to update your compiler.
