### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by matpen** [rbock/sqlpp11-connector-sqlite3#33]
I receive a warning about "unused parameter" when compiling code including `serializer.h': the line is [this](https://github.com/rbock/sqlpp11-connector-sqlite3/blob/bc2f05bc7411c9b9755a4410d317316e851afd18/include/sqlpp11/sqlite3/serializer.h#L72), but I suspect [this](https://github.com/rbock/sqlpp11-connector-sqlite3/blob/bc2f05bc7411c9b9755a4410d317316e851afd18/include/sqlpp11/sqlite3/serializer.h#L59) line (and maybe others in the same file) will issue the same warning (although it does not get compiled due to my settings).

I believe it is safe to delete the argument names?

**Comment by rbock** [comment]
That should be perfectly fine, indeed. Do you want to create pull request?

**Comment by rbock** [comment]
Fixed in develop
