### ISSUE TITLE
Upon compiling with VStudio 2017 get many errors

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-sqlite3#36]
Dear Roland,

When compiling project Sqlpp11Sqlite3SelectTest, I get these errors in VStudio 2017 version 15.3.2:

>
     error C3546: '...': there are no parameter packs available to expand (in sqlpp11/statement.h(166))
>
>
     error C3546: '...': there are no parameter packs available to expand (in sqlpp11/statement.h(173):
>
>
    error C3546: '...': there are no parameter packs available to expand (in sqlpp11/statement.h(179)
>
>
    error C2903: '_base_t': symbol is neither a class template nor a function template (in sqlpp11/statement.h(179)
>

>
    error C2903: '_base_t': symbol is neither a class template nor a function template (in sqlpp11/statement.h(258)
>

Any ideas?

Regards,
Juan Dent

**Comment by rbock** [comment]
Dear Juan,

This is a bug in VS2017 15.3, see

https://developercommunity.visualstudio.com/content/problem/95983/c-vs152-153-regression-in-variadic-template-argume.html

as reported by @egorpugin, see also here

https://github.com/rbock/sqlpp11/issues/181

I see no way to work around this.

Best,

Roland

**Comment by juandent** [comment]
Dear Roland,
Well, we will have to wait I guess!!

Regards,
Juan

**Comment by juandent** [comment]
Dear Roland,
The code compiles in the latest preview of Visual Studio (v 15.5.0 preview 5)... 
Still have to wait until they merge this to a definite release but one can work (at least)...

**Comment by rbock** [comment]
Thanks for the update Juan!

That is very good news.

**Comment by juandent** [comment]
Microsoft has finally corrected the compiler bugs that created this issue. Version 15.5.0 of Visual Studio 2017 can be downloaded from **https://www.visualstudio.com/downloads** where you should select Free Donwload in the Visual Studio Community Edition section.

**Comment by rbock** [comment]
Thanks for the information and the link!

**Comment by juandent** [comment]
You are very welcome!!
