### ISSUE TITLE
sqlite compilation

### ISSUE THREAD

**Issue by ericLemanissier** [rbock/sqlpp11-connector-sqlite3#40]
Is there a way to compile and link sqlite directly with the connector, instead of linking to a precompiled library ?

**Comment by rbock** [comment]
You mean using the sqlite source code and building everything into one library (or even combining all of it with your code at once)?

Sure, that's possible. Writing your own or adjusting the existing CMake files should be easy.

**Comment by rbock** [comment]
I guess you were successful?

If not, please open a new issue with the remaining stumbling blocks :-)
