### ISSUE TITLE
Only one sqlcipher include directory is set in CMakeLists.txt

### ISSUE THREAD

**Issue by theodelrieu** [rbock/sqlpp11-connector-sqlite3#42]
~~Seems like a typo at line 46: `set (SQLITE3_INCLUDE_DIRS "${SQLCIPHER_INCLUDE_DIR}" )`~~

~~I think a `S` is missing~~

EDIT: I've spent some time digging, and found what went wrong.
The library uses `#include <sqlite3.h>`, but the `FindSQLCipher.cmake` has a problem:

```cmake
find_path(SQLCIPHER_INCLUDE_DIR NAMES sqlcipher/sqlite3.h
  PATHS
  ${PC_SQLCIPHER_INCLUDEDIR}
  ${PC_SQLCIPHER_INCLUDE_DIRS}
  ${CMAKE_INCLUDE_PATH}
)
```

Thus I cannot build the tests because it's looking for headers inside the `include` folder, not `include/sqlcipher`.
I've replaced it with: 

```cmake
find_path(SQLCIPHER_INCLUDE_DIR NAMES sqlite3.h
  PATH_SUFFIXES sqlcipher
  PATHS
  ${PC_SQLCIPHER_INCLUDEDIR}
  ${PC_SQLCIPHER_INCLUDE_DIRS}
  ${CMAKE_INCLUDE_PATH}
)
```

Though I have other issues, my sqlcipher is built with openssl, the find_package is unable to find libeay32.lib and ssleay32 so the tests cannot be built.

**Comment by rbock** [comment]
Wouldn't it be better to make the code include `sqlcipher/sqlite3.h`? Otherwise there is always the risk of accidentally including the "normal"  `sqlite3.h` by accident.

Are the two `sqlite3.h` essentially the same anyway? That might explain why this hasn't come up earlier.

**Comment by theodelrieu** [comment]
Yes I believe that would be the appropriate solution.

SQLCipher is a SQLite extension, they're based on the SQLite codebase. The API are exactly the same.

**Comment by rbock** [comment]
Pushed a possible solution to develop.

**Comment by theodelrieu** [comment]
I'll try that tonight, thanks!

**Comment by theodelrieu** [comment]
It almost works, you left the `PATH_SUFFIXES sqlcipher` in `FindSQLCipher.cmake`.
Also, I built SQLCipher with OpenSSL support, so I've got some unresolved symbols when compiling the sqlite3 connector.

Adding a `SQLCIPHER_WITH_OPENSSL` option should do the trick (with an appropriate `find_package` too)

**Comment by rbock** [comment]
Arrgh, tricked myself in `FindSQLCipher.cmake`.

I'd welcome a pull request for the `SQLCIPHER_WITH_OPENSSL` option.

**Comment by theodelrieu** [comment]
I was mistaken about the `PATH_SUFFIXES`, it's correct :)

 I'm currently adding shared build support, along with the `SQLCIPHER_WITH_OPENSSL`.

**Comment by rbock** [comment]
Are you sure? This is now on develop:

```
find_path(SQLCIPHER_INCLUDE_DIRS NAMES sqlcipher/sqlite3.h
  PATHS
  ${PC_SQLCIPHER_INCLUDEDIR}
  ${PC_SQLCIPHER_INCLUDE_DIRS}
  ${CMAKE_INCLUDE_PATH}
)
```

Since the library now includes `<sqlcipher/sqlite3.h>`, that seemed reasonable to me. But as mentioned before, my cmake skills are not exactly well developed.

**Comment by theodelrieu** [comment]
Neither are mine, but I'll try to improve them this week-end. Also I've been playing with Conan, so it's likely that I've tripped somewhere too.

**Comment by rbock** [comment]
The sqlite3 connector got merged into sqlpp11.

Closing all issues here, before archiving. If this issue is still relevant, please re-file for sqlpp11.
