### ISSUE TITLE
find_package and sqlpp11

### ISSUE THREAD

**Issue by theodelrieu** [rbock/sqlpp11-connector-sqlite3#44]
Hi,

I was wondering why this library was not calling `find_package(sqlpp11)` as it's doing right now with `HinnantDate`, `Sqlite3`, and `SQLCipher`. That would make more sense IMO, and remove the duplicated `FindHinnantDate.cmake` file, which is already present in `sqlpp11/cmake`.

Also, I'm using Conan and I had to heavily patch the `CMakeLists.txt` to use my previously built dependencies (sqlcipher etc...). Having a `find_package` for each dependency would reduce the number of patches.

What do you think about it?

**Comment by rbock** [comment]
I am all for it. However, I am almost illiterate when it comes to cmake.

I would welcome a pull request :-)

**Comment by theodelrieu** [comment]
I'm working on it :)
