### ISSUE TITLE
Cannot build with date v2.3

### ISSUE THREAD

**Issue by egorpugin** [rbock/sqlpp11-connector-sqlite3#46]
Hi!

See:
https://github.com/rbock/sqlpp11-connector-sqlite3/blob/master/src/prepared_statement.cpp#L29
and other places with `#include <date.h>`.
Since 2.3 there must be `#include <date/date.h>`.
https://github.com/HowardHinnant/date

**Comment by rbock** [comment]
Hi, sorry for the late reply.

I just updated to 2.3. All I had to do was re-run cmake:

In my case:
```
cmake .. -DSQLCIPHER=ON -DHinnantDate_ROOT_DIR=/home/rbock/projects/date
```

It probably makes sense to switch to including `date/date.h` some time soon.

**Comment by egorpugin** [comment]
> It probably makes sense to switch to including date/date.h some time soon.

This is better and correct solution.

You have also `include` dir in sqlpp11, and include path is set to it, so we write `#include <sqlpp11/some_header>`, not `#include <some_header>`.
Now date also has `include` dir, so we must write `#include <date/date.h>`.

**Comment by rbock** [comment]
Agreed, I am just a little hesitant because the update in the date library is still quite recent.

**Comment by egorpugin** [comment]
Date is v2.4 now with the same solid folder structure.
https://github.com/HowardHinnant/date/releases
Maybe it's the time?

**Comment by rbock** [comment]
Thanks for the reminder!

Yes, I guess it is about time. Would you like to write pull requests for sqlpp11 and the sqlite connector?

**Comment by egorpugin** [comment]
Sure. I'll do it later today.

**Comment by egorpugin** [comment]
See
https://github.com/rbock/sqlpp11/pull/212
https://github.com/rbock/sqlpp11-connector-sqlite3/pull/52

**Comment by egorpugin** [comment]
Thanks!
Closing this.
