### ISSUE TITLE
how to call sqlite functions that take parameters?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-sqlite3#47]
So far, awesome! I am playing around with the samples/tests using the latest preview of VS 2017 --- just great!
Only one question if I may, how can one call a sqlite function that expects a column's values?

For instance: trim(X), where X is a varchar column?

`  std::cerr << "ltrim: "
	  << db(select(sqlpp::verbatim<sqlpp::varchar>("ltrim()").as(tab.beta))).front().beta
	  << std::endl;
`

Regards,
Juan

**Comment by rbock** [comment]
Hi Juan,

Glad you're happy :-)

There are at least three ways to do the `ltrim`:

1. The hack:
   ```
      "ltrim(beta)"
   ```
   This will break with the column renaming.
1. The quick and dirty way:
   ```
      "ltrim(" + get_sql_name(tab.beta) + ")"
   ```
   This will `get_sql_name` will return the column name (e.g. `beta`, but not `tab_sample.beta`).
1. The clean way:
   You provide a push request to add `ltrim` to sqlpp11. It is not hard. Look at functions like `max`. It is mostly boilerplate.
   
Neither the first nor the second version will tell you at compile time that you need to add `.from(tab)` to your query. Thus, I strongly suggest going for the last version. Let me know if you need help with that.


Cheers,

Roland

**Comment by juandent** [comment]
I believe I have a very first version of trim that works. However, it does not deal with the possibility of having 2 arguments (TRIM(x,y)).
Forgive my ignorance: how do I proceed with the push request? And it would need to be on the sqlpp11 project correct?

I also believe that a flag is necessary so as to handle the 2 parameter format of TRIM.

BTW, are you aware Microsoft released the final release version of which we only had a preview in a past few days? And it compiles this connector perfectly!

Cheers,
Juan

**Comment by rbock** [comment]
Hi Juan,

That's both awesome news!

Regarding the MSVC release: If you have a download link or a link to release notes etc, please post them in the respective tickets in this repo and the sqlpp11 one.

Regarding trim:
Looking at some documentation, it seems that adding a second parameter will be considerably more complex and require some connector-specific changes:

  https://sqlite.org/lang_corefunc.html#ltrim
  https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_trim
  https://www.postgresql.org/docs/9.1/static/functions-string.html
  https://docs.microsoft.com/en-us/sql/t-sql/functions/trim-transact-sql

If you don't need that right now, I would suggest pushing the single-argument version first. We can always add a second overload with two arguments later.

github has excellent documentation on how to create pull requests, see for instance: https://help.github.com/articles/creating-a-pull-request/

Best,

Roland

**Comment by juandent** [comment]
Dear Roland,

I created a pull request in sqlpp11. Please check it out and let me know if it is fine.
I tested it and worked.

Regards,
Juan Dent
