### ISSUE TITLE
A compiler problem in MSVC is not allowing a build in the latest version of Visual Studio

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-sqlite3#49]
File type_traits.h has tons of compilation errors, all with the same pattern:

`template <typename T>
    struct column_spec_can_be_null_impl<
        T,
        typename std::enable_if<T::_traits::_tags::template count<tag::can_be_null>()>::type> // ERROR HERE
    {
      using type = std::true_type;
    };`

The marked line shows 3 errors:

>  1- error C2064: term does not evaluate to a function taking 0 arguments
> 2- error C2039: 'type': is not a member of 'std::enable_if<false,void>'
> 3- error C2146: syntax error: missing '>' before identifier 'type'

So I interpret that the term that does not evaluate to a function ends with `tag::can_be_null>()>::type`
Why error #2? Seems SFINAE to me and should not be an error (after all std::enable_if<false,...>)

These problems appear in the latest release (15.5.1) as well as the latest preview (15.6.0 preview 1)

So frustrating!

Any insights as to what may be going on? Compiler bug or code problem?

Regards,
Juan

P.S.: I did a pull request of only the TRIM.h file (sqlpp11) and of the header that contains aggregate functions and of the checks without the #if/endifs here.
Please tell me if they work well in your end.

**Comment by rbock** [comment]
Hi Juan,

That does not bode well...

Questions:
 - This happens with code that compiled fine with 15.5.0?
 - Can you try the equivalent of `g++ -I ../include/ ../include/sqlpp11/type_traits.h`, please?
 - In case type_traits.h alone compiles fine, do you have way to figure out which type `T` is?

Thanks,

Roland

**Comment by juandent** [comment]
Hi Roland,

No it certainly does not look good. It would be great if we could produce a tiny sample that exemplifies the non-compiling code so I could submit it to Microsoft.

As to your questions:
* it happens with code that compiled fin with 15.5.0
* Tried but did not work
* type_traits.h does not compile

However, it is peculiar that enable_if is enable_if<false, void> which gives the error ... seems SFINAE should not take this as an error. The problem seems related to enable_if (?)

Regards,
Juan

**Comment by juandent** [comment]
To be sure that there was no change in the code, I cloned this and sqlpp11 again and tried recompiling, but the problem persists...

Regards,
Juan

**Comment by rbock** [comment]
Not sure what you mean by "Tried by did not work". Do you get the same error messages when you try to compile `type_traits.h`?

If VC does not compile headers, try something like

```
#include <sqlpp11/type_traits.h>
int main() {}
```

If that produces the same error kind of error messages, then it should be easy to create a small sample.

Best,

Roland

**Comment by juandent** [comment]
Hi Roland,

Created the cpp file per your suggestion and the errors are identical. I should point out that the errors occur at 2 places:

`namespace tag
  {
    struct can_be_null
    {
    };
  }  // namespace tag

  namespace detail
  {
    template <typename T, typename Enable = void>
    struct column_spec_can_be_null_impl
    {
      using type = std::false_type;
    };
    template <typename T>
    struct column_spec_can_be_null_impl<
        T,
        typename std::enable_if<T::_traits::_tags::template count<tag::can_be_null>()>::type>
    {
      using type = std::true_type;
    };
  }  // namespace detail
  template <typename T>
  using column_spec_can_be_null_t = typename detail::column_spec_can_be_null_impl<T>::type;`

and at each use of the SQLPP_VALUE_TRAIT_GENERATOR macro.

This source DOES  not use any of the new code relating to TRIM.

And, I have created the following code that seems to exemplify the problem:

`namespace tag
{
	struct can_be_null
	{
	};
}  // namespace tag

namespace detail
{
	template <typename T, typename Enable = void>
	struct column_spec_can_be_null_impl
	{
		using type = std::false_type;
	};
	template <typename T>
	struct column_spec_can_be_null_impl<
		T,
		typename std::enable_if<T::_traits::_tags::template count<tag::can_be_null>()>::type> // ERROR
	{
		using type = std::true_type;
	};
}  // namespace detail
`

Where the errors are (like before) and occurring at the  line marked ERROR:

* error C2064: term does not evaluate to a function taking 0 arguments
* error C2039: 'type': is not a member of 'std::enable_if<false,void>'
*  note: see declaration of 'std::enable_if<false,void>'
* error C2146: syntax error: missing '>' before identifier 'type'

The fact that type is not a member of std::enable_if<false,void> should not generate an error. According to my understanding, by SFINAE, this should not generate error. (what's your take on this?)

Regards,
Juan

**Comment by rbock** [comment]
Great work on isolating the problem.

This is legit code. In "good" cases, `_tags` will be a type_set which have a static constexpr method called `count` which takes no arguments.

Can you file a bug report for VC?

Thanks,

Roland

**Comment by juandent** [comment]
Hi Roland 

Will certainly report this to Microsoft

Regards
Juan

**Comment by rbock** [comment]
Hi Juan,

Could you try with the current develop branch of sqlpp11, please? At the very least, it should give different error messages, now.

Best,

Roland

**Comment by rbock** [comment]
AppVeyor is happy now. Thanks to the MS team for pointing me in the right direction!

**Comment by juandent** [comment]
Hi Roland,

the develop branch of sqlpp11 compiles with NO errors!!

I am going to clone the current connector for sqlite3 to see if that works as well. I assume you made changes with the help of MS team and maybe everything will compile now.

Will let you know!

Cheers,
Juan

**Comment by rbock** [comment]
After fixing a small issue in CMakeLists.txt, it should be fine now...
