### ISSUE TITLE
transaction_t move constructor

### ISSUE THREAD

**Issue by dirkvdb** [rbock/sqlpp11-connector-sqlite3#59]
I just ran into an issue when moving a transaction object

the move constructor is implemented as `=default`
this leaves the _finished member untouched after the move and causes the destructor of the moved from object to rollback the transaction.

changing the transaction_t move constructor to
```
transaction_t(transaction_t&& other)
: _db(other._db)
, _report_unfinished_transaction(other._report_unfinished_transaction)
, _finished(other._finished)
{
    other._finished = true;
}
```

Fixes this issue

**Comment by rbock** [comment]
Good find!
Would you like to create a pull request?

**Comment by dirkvdb** [comment]
Oops, I assumed the transaction logic was part of the connector but it is in the sqlpp11 main repo.
I created a pull request over there: https://github.com/rbock/sqlpp11/pull/240
