### ISSUE TITLE
support for mobile platforms? 

### ISSUE THREAD

**Issue by CingKong** [rbock/sqlpp11-connector-sqlite3#62]

**Comment by rbock** [comment]
I have no personal experience using the library on mobile devices, but I see no reason why it should not work.

**Comment by CingKong** [comment]
so it means you dont use platform specific apis at all?
so sad i have no enough dick space to set up android development environment right now, cant test if it compiles.

**Comment by CingKong** [comment]
successfully built the library for iOS using Qt Creator, not sure if its usable.

build for mac os using cmake directly produced a much bigger sized library than using cmake with Qt Creator, not sure what caused this.

i knew a little about android developing, but android studio changed a lot, now i have no idea how to compile the library at all

i think thats it for this issue for now :)

**Comment by rbock** [comment]
Thanks for the information.

I would suspect that QtCreator strips debug information in your settings while cmake does not?

**Comment by CingKong** [comment]
i have no idea how QtCreator works xD
