### ISSUE TITLE
Is sqlite2cpp.py capable of translating any SQL that runs in sqlite3?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-sqlite3#64]
How limited (or not) is the sqlite2cpp.py file when it comes to translating any SQL that runs in sqlite3? Or, is it preferable to use ddl2cpp?
In other words, how complete is it?

Regards,
Juan Dent

**Comment by rbock** [comment]
Hi Juan,

Given that `sqlite2cpp` is based on sqlite directly, I would expect it to be pretty complete in terms of parsing DDLs. Whether there are things missing in the interpretation of the parsed DDLs I don't know.

But if you stumble over something, it should be quite easy to fix.

Cheers,

Roland
