### ISSUE TITLE
How to use in my project?

### ISSUE THREAD

**Issue by shanpenghui** [rbock/sqlpp11-connector-sqlite3#65]
Hi, i want to use it as a library of my project, but i try some ways that failed many times. Is there any example or tutorial to explain how to use or install?

**Comment by rbock** [comment]
Hi. That is rather unspecific. Can you give me a few more details?

I assume you started with https://github.com/rbock/sqlpp11, first?

**Comment by shanpenghui** [comment]
Hi, @rbock ,I use it in my ros project,below is my CMakeList:
`
cmake_minimum_required(VERSION 3.2)
project(demo)

SET(CMAKE_CXX_FLAGS "-std=c++11 -pthread ")

find_package(catkin REQUIRED COMPONENTS
  nav_msgs
  roscpp
  std_msgs
)

find_package(Threads)
find_package(OpenSSL)

catkin_package()

include_directories(
 include
  ${catkin_INCLUDE_DIRS}
)
include_directories( ${Boost_INCLUDE_DIR} )

 add_executable(${PROJECT_NAME}_node
         src/demo_node.cpp
         src/islam.cpp
         include/file/file.cpp
         src/bind_result.cpp
         src/connection.cpp
         src/prepared_statement.cpp
         include/sqlite3/sqlite3.c
         )

 target_link_libraries(${PROJECT_NAME}_node
   ${catkin_LIBRARIES}
         ${Boost_LIBRARIES}
         ${CMAKE_THREAD_LIBS_INIT} sqlite3 dl
 )
`
And i put bind_reslut.cpp/connection.cpp/prepared_statement.cpp and its .h file in my dir /src.
Compile error display like that:
`
====================[ Build | demo_node | Debug ]===============================
/home/sph/Downloads/clion-2019.1/bin/cmake/linux/bin/cmake --build /home/sph/CLionProjects/demo/src/cmake-build-debug --target demo_node -- -j 2
Scanning dependencies of target demo_node
[ 25%] Building CXX object demo/CMakeFiles/demo_node.dir/src/islam.cpp.o
[ 25%] Building CXX object demo/CMakeFiles/demo_node.dir/src/demo_node.cpp.o
[ 37%] Building CXX object demo/CMakeFiles/demo_node.dir/include/file/file.cpp.o
[ 50%] Building CXX object demo/CMakeFiles/demo_node.dir/src/bind_result.cpp.o
[ 62%] Building CXX object demo/CMakeFiles/demo_node.dir/src/connection.cpp.o
[ 75%] Building CXX object demo/CMakeFiles/demo_node.dir/src/prepared_statement.cpp.o
[ 87%] Building C object demo/CMakeFiles/demo_node.dir/include/sqlite3/sqlite3.c.o
[100%] Linking CXX executable ../devel/lib/demo/demo_node
CMakeFiles/demo_node.dir/src/connection.cpp.o: In function `sqlpp::sqlite3::connection::connection(sqlpp::sqlite3::connection_config)':
/home/sph/CLionProjects/demo/src/demo/src/connection.cpp:88: undefined reference to `sqlpp::sqlite3::detail::connection_handle::connection_handle(sqlpp::sqlite3::connection_config)'
CMakeFiles/demo_node.dir/src/connection.cpp.o: In function `std::default_delete<sqlpp::sqlite3::detail::connection_handle>::operator()(sqlpp::sqlite3::detail::connection_handle*) const':
/usr/include/c++/7/bits/unique_ptr.h:78: undefined reference to `sqlpp::sqlite3::detail::connection_handle::~connection_handle()'
collect2: error: ld returned 1 exit status
demo/CMakeFiles/demo_node.dir/build.make:192: recipe for target 'devel/lib/demo/demo_node' failed
make[3]: *** [devel/lib/demo/demo_node] Error 1
CMakeFiles/Makefile2:1241: recipe for target 'demo/CMakeFiles/demo_node.dir/all' failed
make[2]: *** [demo/CMakeFiles/demo_node.dir/all] Error 2
CMakeFiles/Makefile2:1253: recipe for target 'demo/CMakeFiles/demo_node.dir/rule' failed
make[1]: *** [demo/CMakeFiles/demo_node.dir/rule] Error 2
Makefile:630: recipe for target 'demo_node' failed
make: *** [demo_node] Error 2
`
I check for the connection.cpp:88 but I think it's ok.
I don't understand why the /usr/include/c++/7/bits/unique_ptr.h:78: get error 
`undefined reference to 'sqlpp::sqlite3::detail::connection_handle::~connection_handle()'
collect2: error: ld returned 1 exit status.`
Is there mistake in CMakeList?Or i missing any setting?

**Comment by shanpenghui** [comment]
Oh,i forgot to display what i use. I use this code in my project:
`
    sql::connection_config config;
    config.path_to_database = ":memory:";
    config.flags = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE;
    config.debug = true;

    sql::connection db(config);
    std::cerr << __FILE__ << ": " << __LINE__ << std::endl;
    db.execute("CREATE TABLE tab_sample (\
        alpha bigint(20) DEFAULT NULL,\
        beta varchar(255) DEFAULT NULL,\
        gamma bool DEFAULT NULL\
        )");
`

**Comment by shanpenghui** [comment]
finally, i add this into CMakeList and it work success,but i still dont understand the principle.How it work behind that?
target_link_libraries(Sqlpp11Sqlite3${arg} sqlpp11-connector-sqlite3)

**Comment by rbock** [comment]
The connector library is not header-only. You need to link to the compiled library.

In theory, you can also add the individual cpp files to your project, but then you need to add all of them (you only added a few). I would recommend against that, though.

**Comment by shanpenghui** [comment]
Yes, I recognize that i lose some files to compile library.Thanks a lot! helpful suggestion.
