### ISSUE TITLE
Incorrect transaction commit sequence

### ISSUE THREAD

**Issue by egorpugin** [rbock/sqlpp11-connector-sqlite3#66]
See: https://github.com/rbock/sqlpp11-connector-sqlite3/blob/master/src/connection.cpp#L235

Code:
```
db->start_transaction();
SCOPE_EXIT { db->rollback_transaction(false); };
...
db->commit_transaction();
```

`COMMIT` may cause transaction error, but you mark `_transaction_active` variable on line 235 BEFORE commit execution. Now `COMMIT` fails, my SCOPE_EXIT tries to rollback it and now it fails on the line https://github.com/rbock/sqlpp11-connector-sqlite3/blob/master/src/connection.cpp#L242

Sqlite connector thinks that transaction is over, but it is not.

Possible solution: move line 235 after line 237.

**Comment by egorpugin** [comment]
Same for rollback on line 249.

**Comment by rbock** [comment]
Good point.
After the exception is being thrown in `execute_statement` it is unclear whether the transaction is still alive or not. Maybe it would be best to introduce a third state: "unknown".

**Comment by egorpugin** [comment]
Actually, seems for rollback it is the best to keep as is, so second rollback called will properly throw.

**Comment by egorpugin** [comment]
> After the exception is being thrown in execute_statement it is unclear whether the transaction is still alive or not. 

It's better to introduce some SCOPE_EXIT thing, so `_transaction_active` is unset automatically.

**Comment by rbock** [comment]
> > After the exception is being thrown in execute_statement it is unclear whether the transaction is still alive or not.
> 
> It's better to introduce some SCOPE_EXIT thing, so `_transaction_active` is unset automatically.

Why? Are you 100% sure that the transaction is still alive if the commit throws?

**Comment by egorpugin** [comment]
Yes, seems your variant is better.

**Comment by rbock** [comment]
I finally got around to adding a third state. Please check on develop.

**Comment by egorpugin** [comment]
Thank you.
While I switched to `db->execute("BEGIN/COMMIT/ROLLBACK");`, changes look good, maybe I'll give it a try again when more transaction work required.
(it's very hard and subtle for me to repro the issue - it was spurious on CIs)

**Comment by LouisDuVerdier** [comment]
Hello, this might be slightly out of scope of the issue tracker for this project but should we add the same fix to the mysql connector?

**Comment by rbock** [comment]
Hi,

Yes, I guess we should.

I am a little drowned in other tasks right now. Wanna give it a go yourself?

Thanks,

Roland
