### ISSUE TITLE
How to use it with sqlpp::connection_pool

### ISSUE THREAD

**Issue by zamazan4ik** [rbock/sqlpp11-connector-sqlite3#69]
Hi!
Seems like you've missed required `using` or `typedef` for `connection` entity in sqlite3 `connection_config`. Without it I cannot use it with `connection_pool`.

Thank you!

P.S. The same issue I've met with `sqlpp-postgresql-connector`.

**Comment by ZaMaZaN4iK** [comment]
For MySql we have such missing here line: https://github.com/rbock/sqlpp11-connector-mysql/blob/master/include/sqlpp11/mysql/connection_config.h#L39

**Comment by rbock** [comment]
Hi,

Thanks for the report. Can you create a pull request?

Please keep in mind that the connection pool is experimental. Handle with care. Pull requests welcome :-)

Thanks,

Roland

**Comment by ZaMaZaN4iK** [comment]
@rbock Did you have any examples of using `connection_pool` from your library? That's a little bit difficult to use it without examples :(

**Comment by ZaMaZaN4iK** [comment]
Oh way... `connection_pool` doesn't work at all with `sqlpp11-postgresql-connector`, unfortunately. `connection` class from this library have missed several methods inside (like `is_valid`). Without them there is no chance to even compile it.

Can you suggest me any other option for `connection_pool`? Write my own?

**Comment by rbock** [comment]
From the library perspective, the preferred option would be to improve the existing prototype. Maybe you could team up with @MacDue who contributed the latest fix?

Adding the missing functions to the postgresql connector would probably not be difficult either (but I cannot really tell as I am not the maintainer for that one).

**Comment by rbock** [comment]
The sqlite3 connector got merged into sqlpp11.

Closing all issues here, before archiving. If this issue is still relevant, please re-file for sqlpp11.
