### ISSUE TITLE
how to use Select about sqlite3?

### ISSUE THREAD

**Issue by CBHXuTT** [rbock/sqlpp11-connector-sqlite3#75]
When  using the sqllpp about sqlite, I found it don't run execute_statement. So, there is need achieved by myself? And, bind_result_t can't be operated about iteration.
```
    bind_result_t connection::select_impl(const std::string& statement)
    {
      std::unique_ptr<detail::prepared_statement_handle_t> prepared(
          new detail::prepared_statement_handle_t(prepare_statement(*_handle, statement)));
      if (!prepared)
      {
        throw sqlpp::exception("Sqlite3 error: Could not store result set");
      }
// todo ?
      return {std::move(prepared)};
    }
```

**Comment by rbock** [comment]
I took the liberty of formatting the code in your question properly. You are posting library code? Why? If you want to use the library (and not change it), you should have no need to touch it.

You can see how it is done in tests/SampleTest.cpp:

```
namespace sql = sqlpp::sqlite3;
int main()
{
  sql::connection_config config;
  config.path_to_database = ":memory:";
  config.flags = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE;
  config.debug = true;

  sql::connection db(config);
  for (const auto& row : db(select(all_of(tab)).from(tab).unconditionally()))
  {
    std::cerr << "row.alpha: " << row.alpha << ", row.beta: " << row.beta << ", row.gamma: " << row.gamma << std::endl;
  };
}
```

Hope this helps.

**Comment by CBHXuTT** [comment]
Thank you very much!
The example can be executed correctly.
This problemis a question of my understanding, i use sqlite on muti-thread, so i make a connection-pool using unique_ptr. I use the select by ptr->select, there may be some problems here I did not understand. I found the function of select don't execte the prepare_statement.

**Comment by rbock** [comment]
`select()` just creates a representation of a statement. It does not do anything. But you can prepare and execute it.

connection (`db`) in the example is a callable object. Calling it executes the (prepared) statement.

If you want to use explicitly prepared statements, then it would look something like this:

```
const auto prepared_select = db.prepare(select(all_of(tab)).from(tab).unconditionally());
for (const auto& row : db(prepared_select))
{
   std::cerr << "row.alpha: " << row.alpha << ", row.beta: " << row.beta << ", row.gamma: " << row.gamma << std::endl;
};

**Comment by CBHXuTT** [comment]
Ok, Thanks for your quick response!
