### ISSUE TITLE
Explicit unnecessary sqlite3 header inclusion in the IntegralTest.cpp and FloatingPointTest.cpp makes tests fail with libsqlcipher

### ISSUE THREAD

**Issue by yagnasrinath** [rbock/sqlpp11-connector-sqlite3#76]
https://github.com/rbock/sqlpp11-connector-sqlite3/blob/a06d6944a55349fbd0ab0337c45d80c6efa2ff81/tests/IntegralTest.cpp#L37

https://github.com/rbock/sqlpp11-connector-sqlite3/blob/a06d6944a55349fbd0ab0337c45d80c6efa2ff81/tests/FloatingPointTest.cpp#L37

**Comment by rbock** [comment]
Thanks for the report. Would you also like to create a PR for this?

**Comment by yagnasrinath** [comment]
PR: https://github.com/rbock/sqlpp11-connector-sqlite3/pull/78

**Comment by rbock** [comment]
Thanks, PR is merged.
