### ISSUE TITLE
Feature Request: Support for SQLITE_ENABLE_UPDATE_DELETE_LIMIT option which allows delete statement to specify limit

### ISSUE THREAD

**Issue by yagnasrinath** [rbock/sqlpp11-connector-sqlite3#77]
sqlite supports (https://www.sqlite.org/compile.html#enable_update_delete_limit) specifying limit option with the delete statement, when compiled with the specified option. Is there a way this can be supported on the connector?

**Comment by rbock** [comment]
You can do this today by using a `custom_query`, see sqlpp11/tests/CustomQuery.cpp for inspiration.

Can the support be determined at compile time? In that case, we could adjust the update and delete statements accordingly.

**Comment by yagnasrinath** [comment]
@rbock It looks like the code for supporting the option in sqlite repo is behind macros(if def). So, I am not sure if we can detect that at compile time.

https://github.com/sqlite/sqlite/search?q=SQLITE_ENABLE_UPDATE_DELETE_LIMIT&unscoped_q=SQLITE_ENABLE_UPDATE_DELETE_LIMIT

**Comment by rbock** [comment]
I was hoping for some compile-time constant generated in the header, if you are using this flag. You could ask the sqlite3 team if there is a way.

If that is not the case, then I'd say we have the following options:

- Use custom_query
- Write custom versions of `update` and `delete_from` either 
  - just for yourself
  - in a header that somehow indicates that you need to know what you are doing when you use it
  - in combination with a compile time flag such that the limit option is only available when the flag is set.

**Comment by rbock** [comment]
The sqlite3 connector got merged into sqlpp11.

Closing all issues here, before archiving. If this issue is still relevant, please re-file for sqlpp11.
